// <auto-generated />
using System;
using MenSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260605192939_UpdateMenCategories")]
    partial class UpdateMenCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenCategoryId");

                    b.ToTable("MenCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Essential white t-shirt for everyday wear",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 20m,
                            Title = "Classic White Tee"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Bold streetwear graphic t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 25m,
                            Title = "Black Graphic Tee"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic navy blue crew neck t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 22m,
                            Title = "Navy Blue Tee"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Smart striped polo for casual outings",
                            ImageUrl = "https://images.unsplash.com/photo-1581655353564-df123a1eb820?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 35m,
                            Title = "Striped Polo Shirt"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Classic black leather jacket with zip closure",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 150m,
                            Title = "Leather Jacket"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Timeless casual denim jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 89m,
                            Title = "Denim Jacket"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Stylish bomber jacket perfect for autumn",
                            ImageUrl = "https://images.unsplash.com/photo-1520975916090-3105956dac38?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 110m,
                            Title = "Bomber Jacket"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Warm puffer jacket for cold winter days",
                            ImageUrl = "https://images.unsplash.com/photo-1547624643-3bf761b09502?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 130m,
                            Title = "Puffer Jacket"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Modern slim fit blue jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 55m,
                            Title = "Slim Fit Jeans"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Sleek black skinny jeans for a sharp look",
                            ImageUrl = "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 60m,
                            Title = "Black Skinny Jeans"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Comfortable relaxed fit jeans for casual days",
                            ImageUrl = "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 50m,
                            Title = "Relaxed Fit Jeans"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Trendy ripped jeans with distressed details",
                            ImageUrl = "https://images.unsplash.com/photo-1555689502-c4b22d76c56f?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 65m,
                            Title = "Ripped Jeans"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Smart Oxford shirt for office or casual wear",
                            ImageUrl = "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 45m,
                            Title = "Oxford Shirt"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Cozy flannel shirt perfect for weekends",
                            ImageUrl = "https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 38m,
                            Title = "Flannel Shirt"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Light breathable linen shirt for summer",
                            ImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 42m,
                            Title = "Linen Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Elegant black formal shirt for special occasions",
                            ImageUrl = "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 48m,
                            Title = "Black Formal Shirt"
                        });
                });

            modelBuilder.Entity("MenCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tops"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bottoms"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suits & Formalwear"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Outerwear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Swimwear"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessories"
                        });
                });

            modelBuilder.Entity("MenSection.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("MenSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("MenSection.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MenSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("MenCards", b =>
                {
                    b.HasOne("MenCategory", "MenCategory")
                        .WithMany("MenCards")
                        .HasForeignKey("MenCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenCategory");
                });

            modelBuilder.Entity("MenSection.Models.CartItem", b =>
                {
                    b.HasOne("MenSection.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MenSection.Models.OrderItem", b =>
                {
                    b.HasOne("MenSection.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MenCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MenCategory", b =>
                {
                    b.Navigation("MenCards");
                });

            modelBuilder.Entity("MenSection.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("MenSection.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
