// <auto-generated />
using MenSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MenSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260602204644_AddMoreProducts")]
    partial class AddMoreProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MenCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MenCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MenCategoryId");

                    b.ToTable("MenCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Essential white t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 20m,
                            Title = "Classic White Tee"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Streetwear graphic t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 25m,
                            Title = "Black Graphic Tee"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic leather jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 150m,
                            Title = "Leather Jacket"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Casual denim jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1523205771623-e0faa4d2813d?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 89m,
                            Title = "Denim Jacket"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Modern slim fit jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1542272454315-4c01d7abdf4a?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 55m,
                            Title = "Slim Fit Jeans"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sleek black skinny jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1604176354204-9268737828e4?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 60m,
                            Title = "Black Skinny Jeans"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Smart Oxford shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 45m,
                            Title = "Oxford Shirt"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Casual flannel shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1589310243389-96a5483213a8?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 38m,
                            Title = "Flannel Shirt"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Stylish bomber jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1520975916090-3105956dac38?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 110m,
                            Title = "Bomber Jacket"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Light summer linen shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 42m,
                            Title = "Linen Shirt"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Classic white polo shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1618354691373-d851c5c827a4?w=400&q=80",
                            MenCategoryId = 1,
                            Price = 30m,
                            Title = "White Polo Shirt"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Comfortable casual chinos",
                            ImageUrl = "https://images.unsplash.com/photo-1473966968600-fa4cebea7cf0?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 65m,
                            Title = "Casual Chinos"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Warm puffer jacket",
                            ImageUrl = "https://images.unsplash.com/photo-1544966503-7b654b25498d?w=400&q=80",
                            MenCategoryId = 2,
                            Price = 130m,
                            Title = "Puffer Jacket"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Casual striped shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1552374196-1ab2a1c593e8?w=400&q=80",
                            MenCategoryId = 4,
                            Price = 48m,
                            Title = "Striped Shirt"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Modern dark wash jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=400&q=80",
                            MenCategoryId = 3,
                            Price = 70m,
                            Title = "Dark Wash Jeans"
                        });
                });

            modelBuilder.Entity("MenCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MenCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jackets"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shirts"
                        });
                });

            modelBuilder.Entity("MenCards", b =>
                {
                    b.HasOne("MenCategory", "MenCategory")
                        .WithMany("MenCards")
                        .HasForeignKey("MenCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenCategory");
                });

            modelBuilder.Entity("MenCategory", b =>
                {
                    b.Navigation("MenCards");
                });
#pragma warning restore 612, 618
        }
    }
}
