// <auto-generated />
using System;
using KidsSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260607195846_UpdateKidsData")]
    partial class UpdateKidsData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidsCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("KidsProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KidsCategoryId");

                    b.HasIndex("KidsProductTypeId");

                    b.ToTable("KidsCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Soft cotton striped onesie",
                            ImageUrl = "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 1,
                            Price = 12m,
                            Title = "Baby Striped Onesie"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Colourful rainbow bodysuit",
                            ImageUrl = "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 2,
                            Price = 14m,
                            Title = "Baby Rainbow Bodysuit"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Cute floral baby romper",
                            ImageUrl = "https://images.unsplash.com/photo-1607227893600-9bc90f1ead82?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 2,
                            Price = 18m,
                            Title = "Baby Girl Romper"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Soft jersey baby bodysuit",
                            ImageUrl = "https://images.unsplash.com/photo-1574179618836-b7b81b2e1a4d?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 1,
                            Price = 16m,
                            Title = "Baby Boy Bodysuit"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Cosy knitted 2-piece set",
                            ImageUrl = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 2,
                            Price = 22m,
                            Title = "Baby Knit Set"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pretty summer floral dress",
                            ImageUrl = "https://images.unsplash.com/photo-1508766917616-d22f3f1eea14?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 28m,
                            Title = "Girls Floral Dress"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Elegant princess party dress",
                            ImageUrl = "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 35m,
                            Title = "Girls Princess Dress"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Comfortable stretch leggings",
                            ImageUrl = "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 15m,
                            Title = "Girls Leggings"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Light summer sundress",
                            ImageUrl = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 32m,
                            Title = "Girls Sundress"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Classic denim mini skirt",
                            ImageUrl = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 24m,
                            Title = "Girls Denim Skirt"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Trendy puff sleeve blouse",
                            ImageUrl = "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 20m,
                            Title = "Girls Puff Sleeve Top"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic straight-fit jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 28m,
                            Title = "Boys Denim Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Light cotton summer shorts",
                            ImageUrl = "https://images.unsplash.com/photo-1471286174890-9c112ac6f609?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 18m,
                            Title = "Boys Summer Shorts"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Practical multi-pocket shorts",
                            ImageUrl = "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 20m,
                            Title = "Boys Cargo Shorts"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Classic cotton polo shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1519689373923-95a9fa831f2e?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 22m,
                            Title = "Boys Polo Shirt"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Cool graphic print hoodie",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 30m,
                            Title = "Boys Graphic Hoodie"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Smart casual chino trousers",
                            ImageUrl = "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 26m,
                            Title = "Boys Chino Pants"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Sporty baseball-style tee",
                            ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 16m,
                            Title = "Boys Baseball Tee"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Soft star-print pyjama set",
                            ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 2,
                            Price = 22m,
                            Title = "Girls Star Pyjamas"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Fun dinosaur pyjama set",
                            ImageUrl = "https://images.unsplash.com/photo-1586105449897-20b5efeb3233?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 1,
                            Price = 22m,
                            Title = "Boys Dino Pyjamas"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Warm fleece baby sleepsuit",
                            ImageUrl = "https://images.unsplash.com/photo-1567578301402-c43d6dbef7de?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 1,
                            Price = 18m,
                            Title = "Baby Sleepsuit"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Cosy cotton nightgown",
                            ImageUrl = "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 2,
                            Price = 20m,
                            Title = "Girls Nightgown"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Bright one-piece swimsuit",
                            ImageUrl = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80",
                            KidsCategoryId = 5,
                            KidsProductTypeId = 2,
                            Price = 28m,
                            Title = "Girls Swimsuit"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Quick-dry swim shorts",
                            ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80",
                            KidsCategoryId = 5,
                            KidsProductTypeId = 1,
                            Price = 20m,
                            Title = "Boys Swim Shorts"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Colourful two-piece bikini",
                            ImageUrl = "https://images.unsplash.com/photo-1550639525-c97d455acf70?w=400&q=80",
                            KidsCategoryId = 5,
                            KidsProductTypeId = 2,
                            Price = 30m,
                            Title = "Girls Bikini Set"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Lightweight everyday sneakers",
                            ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",
                            KidsCategoryId = 6,
                            KidsProductTypeId = 1,
                            Price = 38m,
                            Title = "Kids Sneakers"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Strappy summer sandals",
                            ImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80",
                            KidsCategoryId = 6,
                            KidsProductTypeId = 2,
                            Price = 28m,
                            Title = "Girls Sandals"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Classic canvas lace-up shoes",
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80",
                            KidsCategoryId = 6,
                            KidsProductTypeId = 1,
                            Price = 32m,
                            Title = "Boys Canvas Shoes"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Waterproof rubber rain boots",
                            ImageUrl = "https://images.unsplash.com/photo-1597248881519-db089b3a0508?w=400&q=80",
                            KidsCategoryId = 6,
                            KidsProductTypeId = 2,
                            Price = 34m,
                            Title = "Kids Rain Boots"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Spacious padded school bag",
                            ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",
                            KidsCategoryId = 7,
                            KidsProductTypeId = 1,
                            Price = 35m,
                            Title = "Kids School Backpack"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Set of 5 colourful hair bows",
                            ImageUrl = "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80",
                            KidsCategoryId = 7,
                            KidsProductTypeId = 2,
                            Price = 12m,
                            Title = "Girls Hair Bow Set"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Wide-brim UV protection hat",
                            ImageUrl = "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=400&q=80",
                            KidsCategoryId = 7,
                            KidsProductTypeId = 1,
                            Price = 16m,
                            Title = "Kids Sun Hat"
                        },
                        new
                        {
                            Id = 33,
                            Description = "UV400 kids sunglasses",
                            ImageUrl = "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=400&q=80",
                            KidsCategoryId = 7,
                            KidsProductTypeId = 2,
                            Price = 14m,
                            Title = "Kids Sunglasses"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Adorable patterned baby onesie",
                            DiscountPercent = 30,
                            ImageUrl = "https://images.unsplash.com/photo-1519689373923-95a9fa831f2e?w=400&q=80",
                            KidsCategoryId = 8,
                            KidsProductTypeId = 1,
                            Price = 20m,
                            Title = "Baby Patterned Onesie"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Light floral girls dress",
                            DiscountPercent = 25,
                            ImageUrl = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80",
                            KidsCategoryId = 8,
                            KidsProductTypeId = 2,
                            Price = 35m,
                            Title = "Girls Summer Dress"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Warm zip-up boys hoodie",
                            DiscountPercent = 20,
                            ImageUrl = "https://images.unsplash.com/photo-1471286174890-9c112ac6f609?w=400&q=80",
                            KidsCategoryId = 8,
                            KidsProductTypeId = 1,
                            Price = 32m,
                            Title = "Boys Zip Hoodie"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Classic canvas trainers",
                            DiscountPercent = 35,
                            ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80",
                            KidsCategoryId = 8,
                            KidsProductTypeId = 2,
                            Price = 40m,
                            Title = "Kids Canvas Trainers"
                        });
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Baby"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Girls"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Boys"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sleepwear"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Swimwear"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Footwear"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Accessories"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Sale"
                        });
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boys"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Girls"
                        });
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.HasOne("KidsCategory", "KidsCategory")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsSection.Models.KidsProductType", "KidsProductType")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KidsCategory");

                    b.Navigation("KidsProductType");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.HasOne("KidsSection.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.HasOne("KidsSection.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
