// <auto-generated />
using System;
using KidsSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260609000003_RemoveSleepwearAddImages")]
    partial class RemoveSleepwearAddImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").HasColumnType("nvarchar(max)");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("DiscountPercent").HasColumnType("int");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("KidsCategoryId").HasColumnType("int");
                    b.Property<int>("KidsProductTypeId").HasColumnType("int");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("KidsCategoryId");
                    b.HasIndex("KidsProductTypeId");
                    b.ToTable("KidsCards");

                    b.HasData(
                        // Baby (1, 5, 9, 10, 11)
                        new { Id = 1,  Title = "Baby Striped Onesie",    Description = "Soft cotton striped onesie",       ImageUrl = "https://image.hm.com/assets/hm/8c/04/8c04c5efaa10c9ce45aa90a0736a3f655380e82d.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 12m },
                        new { Id = 5,  Title = "Baby Rainbow Bodysuit",  Description = "Colourful rainbow bodysuit",       ImageUrl = "https://image.hm.com/assets/hm/42/f4/42f4c83ce439dacd1f7139ef729670df582b0fe0.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 9,  Title = "Baby Girl Romper",       Description = "Cute floral baby romper",          ImageUrl = "https://image.hm.com/assets/hm/c9/e0/c9e006d06dccb847daaac634ec3acac6c17807f5.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 10, Title = "Baby Boy Bodysuit",      Description = "Soft jersey baby bodysuit",        ImageUrl = "https://image.hm.com/assets/hm/d8/1e/d81e720a2bb94a1f788417943316de657e36d28a.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 11, Title = "Baby Knit Set",          Description = "Cosy knitted 2-piece set",         ImageUrl = "https://image.hm.com/assets/hm/1b/68/1b68a32d8c0c25a3570a41bf5669d2924d36ed4c.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 22m },
                        // Baby extra (38-54)
                        new { Id = 38, Title = "Baby Wrap Cardigan",     Description = "Soft knitted wrap cardigan",       ImageUrl = "https://image.hm.com/assets/hm/29/71/2971d502c2d645aeedf50f3bf379b61c6145ba31.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 39, Title = "Baby Cotton Playsuit",   Description = "Comfortable cotton playsuit",      ImageUrl = "https://image.hm.com/assets/hm/46/0a/460a8b7dacb6f4da9c197f578ee68fa9a7bb3889.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 40, Title = "Baby Ribbed Set",        Description = "Stretchy ribbed two-piece set",    ImageUrl = "https://image.hm.com/assets/hm/70/f1/70f1d834f8fdb12436f90818d681717c8b8545c6.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 41, Title = "Baby Printed Romper",    Description = "Cute printed all-in-one romper",   ImageUrl = "https://image.hm.com/assets/hm/47/6e/476e7c1f6327291192eb8896449d64f9ed0d507b.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 42, Title = "Baby Velour Suit",       Description = "Soft velour top and trouser set",  ImageUrl = "https://image.hm.com/assets/hm/c3/bc/c3bc47a6e0c2465dd9c8814d86cff807eb51d535.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 43, Title = "Baby Patterned Top",     Description = "Colourful patterned long-sleeve",  ImageUrl = "https://image.hm.com/assets/hm/a0/c2/a0c2086db06ee77e222a7b1b51dabc32e5ad8d4e.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 44, Title = "Baby Wrap Body",         Description = "Easy wrap-fastening body",         ImageUrl = "https://image.hm.com/assets/hm/f5/59/f5590708a7b9210721916490df86090944f894dd.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 10m },
                        new { Id = 45, Title = "Baby Quilted Jacket",    Description = "Warm quilted zip-up jacket",       ImageUrl = "https://image.hm.com/assets/hm/52/71/5271451836c9911950b9159ac4ec2454b9387dc3.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 46, Title = "Baby Ruffle Dress",      Description = "Sweet ruffle-trim baby dress",     ImageUrl = "https://image.hm.com/assets/hm/27/e6/27e635b673c9238ebb5567602e00b8e99d062253.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 47, Title = "Baby Hooded Sweatshirt", Description = "Cosy hooded baby sweatshirt",      ImageUrl = "https://image.hm.com/assets/hm/f5/c4/f5c4093647b279f2e047bc80d1c03906067587cc.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 48, Title = "Baby Jersey Leggings",   Description = "Soft stretch jersey leggings",     ImageUrl = "https://image.hm.com/assets/hm/d8/65/d8651d1d12ff9a02d7d7034f05ed8d06ed50d83a.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 49, Title = "Baby Smocked Dress",     Description = "Delicate smocked cotton dress",    ImageUrl = "https://image.hm.com/assets/hm/7b/33/7b33d1353452a261ea6ef4f1c0fa214e2b4cb0b7.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 50, Title = "Baby Terry Joggers",     Description = "Soft terry-cloth jogger pants",    ImageUrl = "https://image.hm.com/assets/hm/60/87/60870dadfcc29e8fb83d60bd0da326c649e677e8.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 51, Title = "Baby Printed Leggings",  Description = "Fun printed stretch leggings",     ImageUrl = "https://image.hm.com/assets/hm/00/9b/009badc880eac55dccf0a48bd0fb8f48642564aa.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 52, Title = "Baby Long-Sleeve Top",   Description = "Soft long-sleeve jersey top",      ImageUrl = "https://image.hm.com/assets/hm/a1/82/a182beecb2b7ae190ed14c3f7b2a1f3d41b3a648.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 53, Title = "Baby Zip Sleepsuit",     Description = "Cosy zip-fastening sleepsuit",     ImageUrl = "https://image.hm.com/assets/hm/cb/fd/cbfdd42d2ae250b84240b35ed1cec21f652c79b9.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 54, Title = "Baby Denim Set",         Description = "Cute denim jacket and trouser set",ImageUrl = "https://image.hm.com/assets/hm/9f/50/9f50289fb4dfd9f089101165011843d712927cd0.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 24m },
                        // Girls (2, 6, 8, 12, 13, 14)
                        new { Id = 2,  Title = "Girls Floral Dress",     Description = "Pretty summer floral dress",       ImageUrl = "https://image.hm.com/assets/hm/ab/15/ab15b8cd3b78ac8ba76768f9223a104734884e52.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 6,  Title = "Girls Princess Dress",   Description = "Elegant princess party dress",     ImageUrl = "https://image.hm.com/assets/hm/de/a1/dea1c170d095bae1a29b0606b6c8574890f87d3e.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 35m },
                        new { Id = 8,  Title = "Girls Leggings",         Description = "Comfortable stretch leggings",     ImageUrl = "https://image.hm.com/assets/hm/4a/f1/4af1c886bf01af58765b5f9a23fc5b704b92460a.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 15m },
                        new { Id = 12, Title = "Girls Sundress",         Description = "Light summer sundress",            ImageUrl = "https://image.hm.com/assets/hm/9f/0e/9f0e60edfbc8d7676ff7c7d1efd9c91505c7644a.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 13, Title = "Girls Denim Skirt",      Description = "Classic denim mini skirt",         ImageUrl = "https://image.hm.com/assets/hm/e6/10/e61010dcc4134f59cf924bd16d37057ca1341391.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 14, Title = "Girls Puff Sleeve Top",  Description = "Trendy puff sleeve blouse",        ImageUrl = "https://image.hm.com/assets/hm/c6/38/c638eb92d0419205d9c79c2bfc03afa13785b5d0.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 20m },
                        // Girls extra (55-69)
                        new { Id = 55, Title = "Girls Embroidered Blouse",Description = "Floral embroidered cotton blouse", ImageUrl = "https://image.hm.com/assets/hm/98/65/98652f9415cabc5ff3c0f3fa1da8363f268bddf3.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 56, Title = "Girls Pleated Skirt",    Description = "Pretty pleated midi skirt",        ImageUrl = "https://image.hm.com/assets/hm/f6/a4/f6a4628ff4e95b72d299ca89fca1a32630b6e60e.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 57, Title = "Girls Ruffle Top",       Description = "Sweet ruffle-trim woven top",      ImageUrl = "https://image.hm.com/assets/hm/54/80/548024730d8318c5e6f7825019b4fabb5c863946.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 58, Title = "Girls Floral Jumpsuit",  Description = "Breezy floral wide-leg jumpsuit",  ImageUrl = "https://image.hm.com/assets/hm/d2/10/d2105e0304ea90b6889809976e0dc7f1f5aafb96.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 59, Title = "Girls Striped T-Shirt",  Description = "Classic striped cotton tee",       ImageUrl = "https://image.hm.com/assets/hm/4c/4b/4c4bf3d062319d0cb0105bbe07429279b4e18e47.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 60, Title = "Girls Velvet Dress",     Description = "Elegant velvet party dress",       ImageUrl = "https://image.hm.com/assets/hm/75/28/7528ca97387e613f693fd30cf8eca320ccd18249.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 42m },
                        new { Id = 61, Title = "Girls Tie-Dye Hoodie",   Description = "Trendy tie-dye zip hoodie",        ImageUrl = "https://image.hm.com/assets/hm/14/d1/14d16be739a74579d3d444d582207291de231fab.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 62, Title = "Girls Printed Joggers",  Description = "Soft printed jersey joggers",      ImageUrl = "https://image.hm.com/assets/hm/70/10/701055386810b6eacef999ffd08091505074a7cb.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 63, Title = "Girls Denim Jacket",     Description = "Classic stone-washed denim jacket",ImageUrl = "https://image.hm.com/assets/hm/27/c8/27c8197972224ca42f051bbc057e172d92ea5d18.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 64, Title = "Girls Knit Cardigan",    Description = "Cosy open-front knit cardigan",    ImageUrl = "https://image.hm.com/assets/hm/14/bc/14bc0bfc778be9d28651e5c1cf0c50dc57190328.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 65, Title = "Girls Sequin Top",       Description = "Sparkly sequin party top",         ImageUrl = "https://image.hm.com/assets/hm/02/94/029443545c4bc9e858c02d0464bb83979ebd2627.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 26m },
                        new { Id = 66, Title = "Girls Wide-Leg Trousers",Description = "Relaxed wide-leg woven trousers",  ImageUrl = "https://image.hm.com/assets/hm/99/c4/99c41f96ad10243a77e929616819991282af2cf3.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 67, Title = "Girls Linen Shorts",     Description = "Lightweight linen pull-on shorts", ImageUrl = "https://image.hm.com/assets/hm/70/c6/70c6e76b648d167c01cc18287bea90368de6c96f.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 68, Title = "Girls Smocked Dress",    Description = "Pretty smocked cotton dress",      ImageUrl = "https://image.hm.com/assets/hm/7e/fa/7efabdd51642bc55f269013d409814214cc186c8.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 36m },
                        new { Id = 69, Title = "Girls Cargo Pants",      Description = "Practical multi-pocket cargo pants",ImageUrl = "https://image.hm.com/assets/hm/13/79/13791492d295b4dbe4914c53751da8524097dd4d.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        // Boys (3, 4, 7, 15, 16, 17, 18)
                        new { Id = 3,  Title = "Boys Denim Jeans",       Description = "Classic straight-fit jeans",       ImageUrl = "https://image.hm.com/assets/hm/4b/19/4b1928a639cd4e4661d4ecc41c0a1e03e27730e7.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 4,  Title = "Boys Summer Shorts",     Description = "Light cotton summer shorts",       ImageUrl = "https://image.hm.com/assets/hm/41/be/41bed8a23b34c5083aa8a0bbbc9755592c6f716b.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 7,  Title = "Boys Cargo Shorts",      Description = "Practical multi-pocket shorts",    ImageUrl = "https://image.hm.com/assets/hm/43/a3/43a3a8d8a832d2d8dd1ad9391904345c387ca380.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 15, Title = "Boys Polo Shirt",        Description = "Classic cotton polo shirt",        ImageUrl = "https://image.hm.com/assets/hm/b6/6e/b66eee7aa009d6f0a0e72b112bc4f99ea6af8d05.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 16, Title = "Boys Graphic Hoodie",    Description = "Cool graphic print hoodie",        ImageUrl = "https://image.hm.com/assets/hm/fa/68/fa6891f65019c07a31f6fe616ccf8e5e53dc26b0.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 17, Title = "Boys Chino Pants",       Description = "Smart casual chino trousers",      ImageUrl = "https://image.hm.com/assets/hm/30/31/3031eb8ab1421f329731d54b8b35b15f1c8b6711.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 18, Title = "Boys Baseball Tee",      Description = "Sporty baseball-style tee",        ImageUrl = "https://image.hm.com/assets/hm/0d/2a/0d2a9d03b5aca7b15f680726b3186520bd1513b6.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        // Boys extra (70-83)
                        new { Id = 70, Title = "Boys Track Jacket",      Description = "Sporty zip-up track jacket",       ImageUrl = "https://image.hm.com/assets/hm/3a/c2/3ac259f71ba8aa0f00f24b485f7b403867906d46.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 36m },
                        new { Id = 71, Title = "Boys Printed Sweatshirt",Description = "Cool graphic print sweatshirt",    ImageUrl = "https://image.hm.com/assets/hm/48/52/485224f72c37e68cc038ab6258f17497c9f60df9.jpg",              KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 72, Title = "Boys Fleece Hoodie",     Description = "Warm soft-fleece pullover hoodie", ImageUrl = "https://image.hm.com/assets/hm/26/13/26131d5d278c6ae384f39a28f82751f80cfe2398.jpg",              KidsCategoryId = 3, KidsProductTypeId = 1, Price = 32m },
                        new { Id = 73, Title = "Boys Slim Fit Jeans",    Description = "Modern slim-fit denim jeans",      ImageUrl = "https://image.hm.com/assets/hm/07/d1/07d1bd3ba0b07a100e305145a11366b902af4877.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 74, Title = "Boys Tech Joggers",      Description = "Lightweight tech-fabric joggers",  ImageUrl = "https://image.hm.com/assets/hm/af/fa/affa1f4d54b02148f78885a480ecf134c48358d5.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 75, Title = "Boys Linen Shirt",       Description = "Breezy linen short-sleeve shirt",  ImageUrl = "https://image.hm.com/assets/hm/89/6d/896d4847603dda4310814f210d29a80850550287.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 76, Title = "Boys Board Shorts",      Description = "Quick-dry patterned board shorts", ImageUrl = "https://image.hm.com/assets/hm/4c/43/4c43460eaad395f95d5355014f708b84f363fc20.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 77, Title = "Boys Zip Fleece",        Description = "Cosy full-zip fleece top",         ImageUrl = "https://image.hm.com/assets/hm/ee/c9/eec90fc1e30eca86b6d5e5ceccc0dacba7d7e7fc.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 34m },
                        new { Id = 78, Title = "Boys Striped Tee",       Description = "Classic navy striped jersey tee",  ImageUrl = "https://image.hm.com/assets/hm/91/8e/918ea167ca1684dffa6226d7155201f9ad496ad8.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 79, Title = "Boys Utility Shorts",    Description = "Cargo-style utility shorts",       ImageUrl = "https://image.hm.com/assets/hm/6b/fb/6bfb18d84e07d78ddbe585acab20f1cded8cc239.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 80, Title = "Boys Quilted Jacket",    Description = "Padded quilted zip jacket",        ImageUrl = "https://image.hm.com/assets/hm/aa/b7/aab746f40e5f92895ddb564434bfca4e7d4beb2e.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 44m },
                        new { Id = 81, Title = "Boys Long-Sleeve Tee",   Description = "Soft jersey long-sleeve tee",      ImageUrl = "https://image.hm.com/assets/hm/ff/73/ff73fe3b24d6b102f95fb3b26c03082e4c33d4a5.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 82, Title = "Boys Sweatpants",        Description = "Comfortable elastic-waist joggers", ImageUrl = "https://image.hm.com/assets/hm/33/62/3362c401e242b81519e76f47bd0792deba934f25.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 83, Title = "Boys Printed Tee",       Description = "Fun graphic printed t-shirt",      ImageUrl = "https://image.hm.com/assets/hm/9c/f9/9cf926b0539bb6de80b13b9e22650fdacccf338b.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m },
                        // Swimwear (23-25, 84-103)
                        new { Id = 23, Title = "Girls Swimsuit",         Description = "Bright one-piece swimsuit",        ImageUrl = "https://image.hm.com/assets/hm/48/aa/48aa0782a07fd5d57fb59a2743db10904a951cc5.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 24, Title = "Boys Swim Shorts",       Description = "Quick-dry swim shorts",            ImageUrl = "https://image.hm.com/assets/hm/41/96/4196605a4cc46336db2af905686f46f34c0c4f2a.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 25, Title = "Girls Bikini Set",       Description = "Colourful two-piece bikini",       ImageUrl = "https://image.hm.com/assets/hm/85/e2/85e2a4ca8980000abb7e5909d3030c8640e4e8cd.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 30m },
                        new { Id = 84,  Title = "Girls Tie-Dye Swimsuit",    Description = "Vibrant tie-dye one-piece swimsuit",  ImageUrl = "https://image.hm.com/assets/hm/1c/0d/1c0dcb2824bdce6899872c79196bd4b86c4bca9c.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 26m },
                        new { Id = 85,  Title = "Boys Striped Swim Trunks",  Description = "Classic striped swim trunks",         ImageUrl = "https://image.hm.com/assets/hm/00/f3/00f3b9957973f25a5b7d753a5fb238e0fa08edb9.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 86,  Title = "Girls Rash Guard Set",      Description = "UV-protective rash guard set",        ImageUrl = "https://image.hm.com/assets/hm/9e/e7/9ee77b03f142149ff85c7cf8110824d54e65dde7.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 30m },
                        new { Id = 87,  Title = "Girls Floral Two-Piece",    Description = "Pretty floral bikini two-piece",      ImageUrl = "https://image.hm.com/assets/hm/ad/da/adda5127cc738ddb93faebc86f34b3c18ae382e1.jpg",              KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 88,  Title = "Boys Shark Swim Shorts",    Description = "Fun shark-print swim shorts",         ImageUrl = "https://image.hm.com/assets/hm/21/67/216743203ff043215e7e2b6b85a7da3284aa31ba.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 24m },
                        new { Id = 89,  Title = "Boys Blue Swim Shorts",     Description = "Bright blue quick-dry swim shorts",   ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwb39aa9b2/pim-static/NI/13253245/13253245_AtomicBlue_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 90,  Title = "Girls UV Swimsuit",         Description = "UPF 50+ sun-protective swimsuit",     ImageUrl = "https://image.hm.com/assets/hm/65/40/6540a32c6967cbad5932853c7c0e7b5b35a2bab2.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 91,  Title = "Girls Polka Dot Bikini",    Description = "Playful polka dot bikini set",        ImageUrl = "https://image.hm.com/assets/hm/85/8f/858fb197d69496b553b2c07415f84e72812e264d.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 30m },
                        new { Id = 92,  Title = "Boys Neon Swim Shorts",     Description = "Bright neon quick-dry shorts",        ImageUrl = "https://image.hm.com/assets/hm/95/f1/95f158948e6bf798b84375d5c667d630fe40b4cc.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 93,  Title = "Girls Navy Swimsuit",       Description = "Classic navy one-piece swimsuit",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwe7134f1e/pim-static/NI/13253322/13253322_NavyBlazer_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 26m },
                        new { Id = 94,  Title = "Boys Tropical Board Shorts", Description = "Vibrant tropical-print board shorts", ImageUrl = "https://image.hm.com/assets/hm/88/86/88861cc5fe5e15253a493829d1d476b5754f9b58.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 95,  Title = "Girls Ruffle Bikini",       Description = "Pretty ruffle-trim bikini set",       ImageUrl = "https://image.hm.com/assets/hm/e4/59/e4598b2a2c745ad8a68cb0a9e5fa286a939f837e.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 96,  Title = "Girls Grey Swimsuit",       Description = "Chic grey one-piece swimsuit",        ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwf7e4800d/pim-static/NI/13253320/13253320_ChateauGray_007.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 97,  Title = "Boys Camo Swim Shorts",     Description = "Cool camouflage swim shorts",         ImageUrl = "https://image.hm.com/assets/hm/35/cc/35cc54031d8ae15aa6fde169ed1315514cdcbdbb.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 24m },
                        new { Id = 98,  Title = "Girls White Bikini",        Description = "Fresh white two-piece bikini",        ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwcf87c070/pim-static/NI/13253242/13253242_BrightWhite_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 99,  Title = "Boys Patterned Swim Trunks", Description = "Bold patterned swim trunks",         ImageUrl = "https://image.hm.com/assets/hm/7a/a5/7aa5c64f0c727c1285a90cbcbf5d1a2f824aafdd.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 100, Title = "Girls Black Bikini",        Description = "Sleek black two-piece bikini",        ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw2677595d/pim-static/NI/13253244/13253244_Black_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 101, Title = "Girls Teal Bikini",         Description = "Vibrant teal two-piece bikini",       ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw5900bf23/pim-static/NI/13253322/13253322_LimpetShell_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 26m },
                        new { Id = 102, Title = "Boys Blue Swim Shorts Set", Description = "Navy blue swim shorts",               ImageUrl = "https://image.hm.com/assets/hm/b9/eb/b9ebe53004b9dda52bf88261e73e620e4bbb1ec9.jpg?imwidth=1260", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 103, Title = "Girls Yellow Swimwear",     Description = "Bright yellow swimwear set",          ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw06f4f2bf/pim-static/NI/13253243/13253243_SafetyYellow_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 24m },
                        // Footwear (26-29, 104-119)
                        new { Id = 26, Title = "Kids Sneakers",          Description = "Lightweight everyday sneakers",    ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dweff593fb/pim-static/NI/13263283/13263283_CrmeDePche_1332588_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 38m },
                        new { Id = 27, Title = "Girls Sandals",          Description = "Strappy summer sandals",           ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw6add5a19/pim-static/NI/13263283/13263283_Black_1332346_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 28, Title = "Boys Canvas Shoes",      Description = "Classic canvas lace-up shoes",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw508a6105/pim-static/NI/13263283/13263283_BegoniaPink_1332350_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 32m },
                        new { Id = 29, Title = "Kids Rain Boots",        Description = "Waterproof rubber rain boots",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwa2c05bb6/pim-static/NI/13263283/13263283_CrmeDePche_1332350_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 34m },
                        new { Id = 104, Title = "Girls Silver Shoes",      Description = "Sparkly silver occasion shoes",   ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw2348eb66/pim-static/NI/13215550/13215550_Silver_1258164_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 34m },
                        new { Id = 105, Title = "Girls Pink Ballet Flats", Description = "Soft pink flat ballet shoes",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw79331750/pim-static/NI/13215550/13215550_Pirouette_1258164_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 30m },
                        new { Id = 106, Title = "Girls Flower Sandals",    Description = "Pretty floral-strap sandals",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw325f98d7/pim-static/NI/13263283/13263283_Nosegay_1332588_007.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 107, Title = "Boys Dark Sneakers",      Description = "Sporty dark-olive sneakers",      ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw6828de1d/pim-static/NI/13263283/13263283_Kalamata_1332346_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 36m },
                        new { Id = 108, Title = "Boys Leather Boots",      Description = "Classic leather ankle boots",     ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dwfdc974fe/pim-static/NI/13231208/13231208_BitterChocolate_008.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 42m },
                        new { Id = 109, Title = "Kids Chelsea Boots",      Description = "Timeless black Chelsea boots",    ImageUrl = "https://www.nameit.com/dw/image/v2/BDTC_PRD/on/demandware.static/-/Sites-pim-catalog/default/dw733c04b6/pim-static/NI/13248115/13248115_BlackCoffee_003.jpg?sw=450&sh=600&strip=false", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 48m },
                        new { Id = 110, Title = "Kids White Trainers",     Description = "Clean white everyday trainers",   ImageUrl = "https://static.zara.net/assets/public/9358/c30c/9b2041acb10a/b687b802c46f/14440830600-e2/14440830600-e2.jpg?ts=1780410309892&w=368", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 36m },
                        new { Id = 111, Title = "Kids Loafer Shoes",       Description = "Smart leather loafer shoes",      ImageUrl = "https://static.zara.net/assets/public/e331/3c48/5a0d44598509/b68f2329d52e/14406830002-032-p/14406830002-032-p.jpg?ts=1780648044489&w=433", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 112, Title = "Girls Slip-On Shoes",     Description = "Easy slip-on casual shoes",       ImageUrl = "https://static.zara.net/assets/public/3eee/2b6b/28b84ceba96e/0cd931a9c71e/14432630001031-p/14432630001031-p.jpg?ts=1776253651151&w=433", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 113, Title = "Kids Leather Sandals",    Description = "Genuine leather summer sandals",  ImageUrl = "https://static.zara.net/assets/public/4968/c952/7d424f3da835/7a85384a015f/14406830002-ult22/14406830002-ult22.jpg?ts=1779291114073&w=433", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 34m },
                        new { Id = 114, Title = "Boys Classic Shoes",      Description = "Smart casual lace-up shoes",      ImageUrl = "https://static.zara.net/assets/public/34d3/77dc/cb244cdfaca2/8464956d9199/14414730001-ult22/14414730001-ult22.jpg?ts=1769439370632&w=433", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 40m },
                        new { Id = 115, Title = "Girls Platform Sneakers", Description = "Trendy platform sole sneakers",   ImageUrl = "https://static.zara.net/assets/public/eddd/b74c/b6d7406fad84/a3b3c5d9c8b1/14506730107034-a1/14506730107034-a1.jpg?ts=1773764178966&w=433", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 116, Title = "Kids Ankle Boots",        Description = "Durable lace-up ankle boots",     ImageUrl = "https://static.zara.net/assets/public/8d31/268b/7be6484aa0ef/b8255f0bb675/16537730002-ult40/16537730002-ult40.jpg?ts=1773832894977&w=284", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 44m },
                        new { Id = 117, Title = "Girls Mary Janes",        Description = "Classic strap Mary Jane shoes",   ImageUrl = "https://static.zara.net/assets/public/9c8a/e38f/c4764ba58ec5/1521c85baba9/16613830612021-p/16613830612021-p.jpg?ts=1779954006356&w=284", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 34m },
                        new { Id = 118, Title = "Boys Sport Sandals",      Description = "Adjustable sport sandals",        ImageUrl = "https://static.zara.net/assets/public/41ae/592b/2e81437eada1/ce85c5f19ca5/16317730001022-a1/16317730001022-a1.jpg?ts=1779954007322&w=284", KidsCategoryId = 6, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 119, Title = "Kids Slip-On Mules",      Description = "Easy-on slip-on mule shoes",      ImageUrl = "https://static.zara.net/assets/public/14fb/cac9/0e3f4757b60b/84f8c287a84c/16637730050023-p/16637730050023-p.jpg?ts=1779954006896&w=184", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 32m },
                        // Accessories (30-33, 120-140)
                        new { Id = 30, Title = "Kids School Backpack",   Description = "Spacious padded school bag",       ImageUrl = "https://static.zara.net/assets/public/a97a/daec/2474439daa46/a30259e1425f/11442730400-e1/11442730400-e1.jpg?ts=1778828996352&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 35m },
                        new { Id = 31, Title = "Girls Hair Bow Set",     Description = "Set of 5 colourful hair bows",    ImageUrl = "https://static.zara.net/assets/public/691d/90ff/65ab41a88c3d/0b7d18d197ff/11226730050-e1/11226730050-e1.jpg?ts=1776779422259&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 32, Title = "Kids Sun Hat",           Description = "Wide-brim UV protection hat",     ImageUrl = "https://static.zara.net/assets/public/41c0/5614/22e04510a756/bf384c42b0e2/11104730002-e1/11104730002-e1.jpg?ts=1764173531641&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 33, Title = "Kids Sunglasses",        Description = "UV400 kids sunglasses",           ImageUrl = "https://static.zara.net/assets/public/cc8b/3a8c/26b84cb58fc2/688ae73f28a4/11113830800-e1/11113830800-e1.jpg?ts=1778773135501&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 120, Title = "Kids Coin Purse",       Description = "Cute zip-up kids coin purse",        ImageUrl = "https://static.zara.net/assets/public/bb86/5fa3/eb3445e88afb/cca5dab00a59/04786558067500-p/04786558067500-p.jpg?ts=1775641852703&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 121, Title = "Kids Hair Clip Set",    Description = "Set of colourful hair clips",        ImageUrl = "https://static.zara.net/assets/public/5971/d8e3/05c5432797cb/6957e4c9003b/06061517061500-p/06061517061500-p.jpg?ts=1776266315739&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 122, Title = "Girls Floral Headband", Description = "Pretty floral elastic headband",    ImageUrl = "https://static.zara.net/assets/public/bedb/8f2b/25b348329f39/49cf48898cba/00475641700101-p/00475641700101-p.jpg?ts=1780323205968&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 10m },
                        new { Id = 123, Title = "Kids Mini Bag",         Description = "Small zip-up mini bag",              ImageUrl = "https://static.zara.net/assets/public/53c3/6137/77f14bfd8185/784f6a474f8e/00009549600-e1/00009549600-e1.jpg?ts=1776062396369&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 124, Title = "Girls Bracelet",        Description = "Delicate beaded bracelet",           ImageUrl = "https://static.zara.net/assets/public/98ef/eab6/86524f0fbc85/3334d47ff2f9/01554512620-090-e1/01554512620-090-e1.jpg?ts=1773661662317&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 125, Title = "Girls Necklace",        Description = "Dainty chain necklace",              ImageUrl = "https://static.zara.net/assets/public/cf55/663b/8c5149f783aa/91e3e3210726/06303533982-090-e1/06303533982-090-e1.jpg?ts=1773651400359&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 126, Title = "Kids Baseball Cap",     Description = "Classic cotton baseball cap",        ImageUrl = "https://static.zara.net/assets/public/fb66/8cf7/19894d87bc46/01ac678c1779/01879568600-e1/01879568600-e1.jpg?ts=1778081678953&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 127, Title = "Kids Bucket Hat",       Description = "Casual sun bucket hat",              ImageUrl = "https://static.zara.net/assets/public/d75e/8929/58aa493abe29/06b92d0c2617/04701548712-e1/04701548712-e1.jpg?ts=1775051598247&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 128, Title = "Kids Canvas Backpack",  Description = "Lightweight canvas school backpack", ImageUrl = "https://static.zara.net/assets/public/c9c9/e523/64be44ec9bec/e489df2c4e18/03772584712-e1/03772584712-e1.jpg?ts=1779369525136&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 129, Title = "Kids Patterned Bag",    Description = "Fun patterned tote bag",             ImageUrl = "https://static.zara.net/assets/public/9693/d22e/486844e09156/bb4bddddb5f9/16705730700-p/16705730700-p.jpg?ts=1776870323637&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 130, Title = "Girls Scrunchie Set",   Description = "Set of elastic scrunchies",          ImageUrl = "https://static.zara.net/assets/public/65d9/65b6/9fbf4c6984c3/7184becd8f0b/00475639252100-p/00475639252100-p.jpg?ts=1780481591545&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 8m  },
                        new { Id = 131, Title = "Kids Leather Belt",     Description = "Classic leather adjustable belt",    ImageUrl = "https://static.zara.net/assets/public/52ec/1281/61834bc0837b/305b6d2eecdd/04319505140-e1/04319505140-e1.jpg?ts=1776951753785&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 132, Title = "Kids Woven Belt",       Description = "Braided woven fabric belt",          ImageUrl = "https://static.zara.net/assets/public/ad30/8cfa/f62f4f9bb0f6/78b6aa838ee9/04319505140100-p/04319505140100-p.jpg?ts=1780411970284&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 133, Title = "Kids Canvas Belt",      Description = "Casual canvas snap belt",            ImageUrl = "https://static.zara.net/assets/public/77c7/2b63/c27747b994df/2312e898542e/04319618330-e1/04319618330-e1.jpg?ts=1773763271100&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 134, Title = "Kids Crossbody Bag",    Description = "Compact mini crossbody bag",         ImageUrl = "https://static.zara.net/assets/public/2610/f5e6/62ac4a2ca93e/571efefc962f/07243591700400-p/07243591700400-p.jpg?ts=1780308105507&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 135, Title = "Girls Charm Bracelet",  Description = "Sweet charm-studded bracelet",       ImageUrl = "https://static.zara.net/assets/public/d6cb/3635/51cf4c29a74c/f839b535266c/00441639600400-p/00441639600400-p.jpg?ts=1780307593315&w=184", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 136, Title = "Kids Mini Wallet",      Description = "Small zip-around wallet",            ImageUrl = "https://static.zara.net/assets/public/bb66/5093/223f45da8b8b/4d5b00c1e42e/05213652400400-p/05213652400400-p.jpg?ts=1779801230585&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 12m },
                        new { Id = 137, Title = "Kids Knit Beanie",      Description = "Soft ribbed-knit beanie hat",        ImageUrl = "https://static.zara.net/assets/public/36d0/c4d9/a50045aba187/1541dc978e62/11161730050-e1/11161730050-e1.jpg?ts=1777381764075&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 138, Title = "Kids Winter Scarf",     Description = "Cosy knitted winter scarf",          ImageUrl = "https://static.zara.net/assets/public/8292/f7ff/b831414ebdaf/5e21da5d4ba5/11144730500-e1/11144730500-e1.jpg?ts=1777284924505&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 139, Title = "Kids Flat Cap",         Description = "Vintage-style flat cap",             ImageUrl = "https://static.zara.net/assets/public/1eef/c9a9/1c434d59a346/92dd1f2930cb/01296602800-e1/01296602800-e1.jpg?ts=1772613562680&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 140, Title = "Kids Bobble Hat",       Description = "Fluffy bobble-top knit hat",         ImageUrl = "https://static.zara.net/assets/public/e91c/a6d9/fd4a4b54ba04/49dc60fe703f/01296650800-e1/01296650800-e1.jpg?ts=1741343790084&w=184", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 14m },
                        // Sale (34-37, 141-165)
                        new { Id = 34, Title = "Baby Patterned Onesie", Description = "Adorable patterned baby onesie", ImageUrl = "https://static.zara.net/assets/public/9550/feb7/981e47c1a61e/4123474202cf/04676601800-e1/04676601800-e1.jpg?ts=1765368970400&w=133", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 20m, DiscountPercent = 30 },
                        new { Id = 35, Title = "Girls Summer Dress",    Description = "Light floral girls dress",       ImageUrl = "https://static.zara.net/assets/public/8c99/e2da/3e1d4b64ad4d/4b31d8f4b115/00722731712300-p/00722731712300-p.jpg?ts=1768471273341&w=133", KidsCategoryId = 8, KidsProductTypeId = 2, Price = 35m, DiscountPercent = 25 },
                        new { Id = 36, Title = "Boys Zip Hoodie",       Description = "Warm zip-up boys hoodie",        ImageUrl = "https://static.zara.net/assets/public/4264/541d/951d47208ccf/ffc7b1b1fba5/05431330526-p/05431330526-p.jpg?ts=1774437078246&w=133", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 32m, DiscountPercent = 20 },
                        new { Id = 37, Title = "Kids Canvas Trainers",  Description = "Classic canvas trainers",        ImageUrl = "https://static.zara.net/assets/public/b02f/0a19/318b43898975/a30f73ae8bff/03854690804-e1/03854690804-e1.jpg?ts=1764607154306&w=133", KidsCategoryId = 8, KidsProductTypeId = 2, Price = 40m, DiscountPercent = 35 },
                        new { Id = 141, Title = "Girls Sale Jacket",       Description = "Discounted girls jacket",          ImageUrl = "https://static.zara.net/assets/public/2498/f971/008448d29cfc/114336728d0f/05431330526-e1/05431330526-e1.jpg?ts=1773076445459&w=133",   KidsCategoryId = 8, KidsProductTypeId = 2, Price = 45m, DiscountPercent = 30 },
                        new { Id = 142, Title = "Boys Sale Hoodie",        Description = "Cosy boys hoodie on sale",         ImageUrl = "https://static.zara.net/assets/public/2d56/8439/d0e84b5aa7e3/c1d75d96ced2/01880761700-e1/01880761700-e1.jpg?ts=1768220947219&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 38m, DiscountPercent = 25 },
                        new { Id = 143, Title = "Kids Sale Set",           Description = "Matching kids two-piece set",      ImageUrl = "https://static.zara.net/assets/public/b449/b446/f5c447a7bcd0/f2ada402ba15/00595625712-e1/00595625712-e1.jpg?ts=1773672686400&w=133",   KidsCategoryId = 8, KidsProductTypeId = 2, Price = 22m, DiscountPercent = 40 },
                        new { Id = 144, Title = "Kids Sale Shorts",        Description = "Light summer shorts on sale",      ImageUrl = "https://static.zara.net/assets/public/0aa6/a182/e1c846dfbd6b/0a348bbbc589/05992770800-p/05992770800-p.jpg?ts=1754563566779&w=133",     KidsCategoryId = 8, KidsProductTypeId = 1, Price = 18m, DiscountPercent = 30 },
                        new { Id = 145, Title = "Girls Sale Trousers",     Description = "Discounted girls trousers",        ImageUrl = "https://static.zara.net/assets/public/f5db/8592/1aac4b39b8d7/5665f2674938/00962611104-p/00962611104-p.jpg?ts=1773749289167&w=133",     KidsCategoryId = 8, KidsProductTypeId = 2, Price = 28m, DiscountPercent = 20 },
                        new { Id = 146, Title = "Kids Sale Shirt",         Description = "Smart shirt at sale price",        ImageUrl = "https://static.zara.net/assets/public/f23e/b11a/9c814316ad6f/b01334c19498/03183401105-e1/03183401105-e1.jpg?ts=1771858593530&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 24m, DiscountPercent = 25 },
                        new { Id = 147, Title = "Kids Sale Jeans",         Description = "Classic jeans on discount",        ImageUrl = "https://static.zara.net/assets/public/e2ca/156d/16214f8ca57c/5cf3ecb54c1d/00318600712-e1/00318600712-e1.jpg?ts=1773654267658&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 32m, DiscountPercent = 20 },
                        new { Id = 148, Title = "Girls Sale Dress",        Description = "Pretty girls dress on sale",       ImageUrl = "https://static.zara.net/assets/public/6b19/bf7a/ec0f41b099fc/6e711b2af378/03854648661-p/03854648661-p.jpg?ts=1770146759919&w=133",     KidsCategoryId = 8, KidsProductTypeId = 2, Price = 40m, DiscountPercent = 35 },
                        new { Id = 149, Title = "Kids Sale Jumpsuit",      Description = "Fun kids jumpsuit at discount",    ImageUrl = "https://static.zara.net/assets/public/06a3/bf69/748c4f9ba685/50b765b6c56b/03391645306100-p/03391645306100-p.jpg?ts=1775461473955&w=133", KidsCategoryId = 8, KidsProductTypeId = 2, Price = 35m, DiscountPercent = 30 },
                        new { Id = 150, Title = "Boys Sale Cardigan",      Description = "Soft boys cardigan on sale",       ImageUrl = "https://static.zara.net/assets/public/b756/3c81/a167425e990a/672589f42064/05644763800-e1/05644763800-e1.jpg?ts=1765543177228&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 30m, DiscountPercent = 25 },
                        new { Id = 151, Title = "Girls Sale Top Set",      Description = "Girls matching top set on sale",   ImageUrl = "https://static.zara.net/assets/public/3a15/a3a7/3f454158bbe0/eaa554d58d29/03391644630100-p/03391644630100-p.jpg?ts=1775461472095&w=133", KidsCategoryId = 8, KidsProductTypeId = 2, Price = 36m, DiscountPercent = 40 },
                        new { Id = 152, Title = "Boys Sale T-Shirt",       Description = "Graphic tee at sale price",        ImageUrl = "https://static.zara.net/assets/public/6508/187e/ca614825ac46/9f00c48f63a9/00962698500-p/00962698500-p.jpg?ts=1772197563850&w=133",     KidsCategoryId = 8, KidsProductTypeId = 1, Price = 18m, DiscountPercent = 20 },
                        new { Id = 153, Title = "Girls Sale Skirt",        Description = "Floaty girls skirt on discount",   ImageUrl = "https://static.zara.net/assets/public/b43d/6c38/262344b18a2f/73648d83c44d/06688604250-e1/06688604250-e1.jpg?ts=1773060298818&w=133",   KidsCategoryId = 8, KidsProductTypeId = 2, Price = 22m, DiscountPercent = 30 },
                        new { Id = 154, Title = "Kids Sale Coat",          Description = "Warm kids coat on sale",           ImageUrl = "https://static.zara.net/assets/public/577e/5cd4/a4334223aefe/60cae71173f4/01443679959-e1/01443679959-e1.jpg?ts=1770381721035&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 55m, DiscountPercent = 40 },
                        new { Id = 155, Title = "Girls Sale Top",          Description = "Casual girls top on discount",     ImageUrl = "https://static.zara.net/assets/public/f577/2027/337a40ffb15d/6b38c69e4a1a/00208606620-p/00208606620-p.jpg?ts=1772795695632&w=133",     KidsCategoryId = 8, KidsProductTypeId = 2, Price = 20m, DiscountPercent = 25 },
                        new { Id = 156, Title = "Kids Sale Jumper",        Description = "Cosy jumper on sale",              ImageUrl = "https://static.zara.net/assets/public/2db2/8c4e/588342d5a016/9750837fd768/03253698615-e1/03253698615-e1.jpg?ts=1775747778751&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 28m, DiscountPercent = 30 },
                        new { Id = 157, Title = "Girls Sale Blouse",       Description = "Pretty blouse at discount",        ImageUrl = "https://static.zara.net/assets/public/09fd/a518/38514ed4872f/15d2491a32be/00208606620-e1/00208606620-e1.jpg?ts=1772038440519&w=133",   KidsCategoryId = 8, KidsProductTypeId = 2, Price = 22m, DiscountPercent = 20 },
                        new { Id = 158, Title = "Kids Sale Sweatshirt",    Description = "Cosy sweatshirt on sale",          ImageUrl = "https://static.zara.net/assets/public/7ce0/55b8/99b2435a847b/9f1112c0ea50/20310421999-000-e1/20310421999-000-e1.jpg?ts=1774456143164&w=133", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 30m, DiscountPercent = 30 },
                        new { Id = 159, Title = "Boys Sale Shorts",        Description = "Boys summer shorts on sale",       ImageUrl = "https://static.zara.net/assets/public/32ce/e069/0b8c449c86e3/9b2c7db28ef5/09144605807-e1/09144605807-e1.jpg?ts=1768549816264&w=133",   KidsCategoryId = 8, KidsProductTypeId = 1, Price = 20m, DiscountPercent = 25 },
                        new { Id = 160, Title = "Girls Sale Leggings",     Description = "Comfy leggings on discount",       ImageUrl = "https://static.zara.net/assets/public/f845/09f7/6e804e5694b4/210fa7a56707/00039705500-p/00039705500-p.jpg?ts=1767875633984&w=133",     KidsCategoryId = 8, KidsProductTypeId = 2, Price = 16m, DiscountPercent = 20 },
                        new { Id = 161, Title = "Kids Sale Joggers",       Description = "Jersey joggers at sale price",     ImageUrl = "https://static.zara.net/assets/public/21f2/fe62/0cab4e47a9f5/b158d3ccedf4/05537601717-p/05537601717-p.jpg?ts=1768466026689&w=133",     KidsCategoryId = 8, KidsProductTypeId = 1, Price = 24m, DiscountPercent = 30 },
                        new { Id = 162, Title = "Girls Sale Sweatpants",   Description = "Soft girls sweatpants on sale",    ImageUrl = "https://static.zara.net/assets/public/27cd/5220/988f44209d62/67e6867137c7/03183619712-p/03183619712-p.jpg?ts=1768466026546&w=133",     KidsCategoryId = 8, KidsProductTypeId = 2, Price = 26m, DiscountPercent = 25 },
                        new { Id = 163, Title = "Kids Sale Parka",         Description = "Warm hooded parka on sale",        ImageUrl = "https://static.zara.net/assets/public/3283/a735/c5ea433f97fd/930d9b184715/12131630700003-p/12131630700003-p.jpg?ts=1759751687728&w=133", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 60m, DiscountPercent = 35 },
                        new { Id = 164, Title = "Boys Sale Shirt",         Description = "Smart boys shirt on discount",     ImageUrl = "https://static.zara.net/assets/public/4bea/6991/7c05463bbf38/fc0544a34810/08054611802-p/08054611802-p.jpg?ts=1768466026653&w=133",     KidsCategoryId = 8, KidsProductTypeId = 1, Price = 24m, DiscountPercent = 20 },
                        new { Id = 165, Title = "Kids Sale Puffer Jacket", Description = "Padded puffer jacket on sale",     ImageUrl = "https://static.zara.net/assets/public/0b63/102c/183f405ca40e/47defd5b9db5/08073700800-e1/08073700800-e1.jpg?ts=1752679754454&w=133",  KidsCategoryId = 8, KidsProductTypeId = 1, Price = 50m, DiscountPercent = 30 }
                    );
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("KidsCategories");
                    b.HasData(
                        new { Id = 1, Name = "Baby" },
                        new { Id = 2, Name = "Girls" },
                        new { Id = 3, Name = "Boys" },
                        new { Id = 5, Name = "Swimwear" },
                        new { Id = 6, Name = "Footwear" },
                        new { Id = 7, Name = "Accessories" },
                        new { Id = 8, Name = "Sale" }
                    );
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("CartId").HasColumnType("int");
                    b.Property<int>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("CartId");
                    b.HasIndex("ProductId");
                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("KidsProductTypes");
                    b.HasData(
                        new { Id = 1, Name = "Boys" },
                        new { Id = 2, Name = "Girls" }
                    );
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<decimal>("TotalPrice").HasColumnType("decimal(18,2)");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("OrderId").HasColumnType("int");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                    b.Property<int>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("OrderId");
                    b.HasIndex("ProductId");
                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.HasOne("KidsCategory", "KidsCategory").WithMany("KidsCards").HasForeignKey("KidsCategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsSection.Models.KidsProductType", "KidsProductType").WithMany("KidsCards").HasForeignKey("KidsProductTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("KidsCategory");
                    b.Navigation("KidsProductType");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.HasOne("KidsSection.Models.Cart", "Cart").WithMany("CartItems").HasForeignKey("CartId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsCards", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Cart");
                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.HasOne("KidsSection.Models.Order", "Order").WithMany("OrderItems").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsCards", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Order");
                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
