// <auto-generated />
using System;
using KidsSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260609000002_AddMoreKidsImages")]
    partial class AddMoreKidsImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Color").HasColumnType("nvarchar(max)");
                    b.Property<string>("Description").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int?>("DiscountPercent").HasColumnType("int");
                    b.Property<string>("ImageUrl").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("KidsCategoryId").HasColumnType("int");
                    b.Property<int>("KidsProductTypeId").HasColumnType("int");
                    b.Property<decimal>("Price").HasPrecision(18, 2).HasColumnType("decimal(18,2)");
                    b.Property<string>("Title").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.HasIndex("KidsCategoryId");
                    b.HasIndex("KidsProductTypeId");
                    b.ToTable("KidsCards");

                    b.HasData(
                        // Baby (original 5)
                        new { Id = 1,  Title = "Baby Striped Onesie",    Description = "Soft cotton striped onesie",       ImageUrl = "https://image.hm.com/assets/hm/8c/04/8c04c5efaa10c9ce45aa90a0736a3f655380e82d.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 12m },
                        new { Id = 5,  Title = "Baby Rainbow Bodysuit",  Description = "Colourful rainbow bodysuit",       ImageUrl = "https://image.hm.com/assets/hm/42/f4/42f4c83ce439dacd1f7139ef729670df582b0fe0.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 9,  Title = "Baby Girl Romper",       Description = "Cute floral baby romper",          ImageUrl = "https://image.hm.com/assets/hm/c9/e0/c9e006d06dccb847daaac634ec3acac6c17807f5.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 10, Title = "Baby Boy Bodysuit",      Description = "Soft jersey baby bodysuit",        ImageUrl = "https://image.hm.com/assets/hm/d8/1e/d81e720a2bb94a1f788417943316de657e36d28a.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 11, Title = "Baby Knit Set",          Description = "Cosy knitted 2-piece set",         ImageUrl = "https://image.hm.com/assets/hm/1b/68/1b68a32d8c0c25a3570a41bf5669d2924d36ed4c.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 22m },
                        // Baby (extra 17)
                        new { Id = 38, Title = "Baby Wrap Cardigan",     Description = "Soft knitted wrap cardigan",       ImageUrl = "https://image.hm.com/assets/hm/29/71/2971d502c2d645aeedf50f3bf379b61c6145ba31.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 39, Title = "Baby Cotton Playsuit",   Description = "Comfortable cotton playsuit",      ImageUrl = "https://image.hm.com/assets/hm/46/0a/460a8b7dacb6f4da9c197f578ee68fa9a7bb3889.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 40, Title = "Baby Ribbed Set",        Description = "Stretchy ribbed two-piece set",    ImageUrl = "https://image.hm.com/assets/hm/70/f1/70f1d834f8fdb12436f90818d681717c8b8545c6.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 41, Title = "Baby Printed Romper",    Description = "Cute printed all-in-one romper",   ImageUrl = "https://image.hm.com/assets/hm/47/6e/476e7c1f6327291192eb8896449d64f9ed0d507b.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 42, Title = "Baby Velour Suit",       Description = "Soft velour top and trouser set",  ImageUrl = "https://image.hm.com/assets/hm/c3/bc/c3bc47a6e0c2465dd9c8814d86cff807eb51d535.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 43, Title = "Baby Patterned Top",     Description = "Colourful patterned long-sleeve",  ImageUrl = "https://image.hm.com/assets/hm/a0/c2/a0c2086db06ee77e222a7b1b51dabc32e5ad8d4e.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 44, Title = "Baby Wrap Body",         Description = "Easy wrap-fastening body",         ImageUrl = "https://image.hm.com/assets/hm/f5/59/f5590708a7b9210721916490df86090944f894dd.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 10m },
                        new { Id = 45, Title = "Baby Quilted Jacket",    Description = "Warm quilted zip-up jacket",       ImageUrl = "https://image.hm.com/assets/hm/52/71/5271451836c9911950b9159ac4ec2454b9387dc3.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 46, Title = "Baby Ruffle Dress",      Description = "Sweet ruffle-trim baby dress",     ImageUrl = "https://image.hm.com/assets/hm/27/e6/27e635b673c9238ebb5567602e00b8e99d062253.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 47, Title = "Baby Hooded Sweatshirt", Description = "Cosy hooded baby sweatshirt",      ImageUrl = "https://image.hm.com/assets/hm/f5/c4/f5c4093647b279f2e047bc80d1c03906067587cc.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 48, Title = "Baby Jersey Leggings",   Description = "Soft stretch jersey leggings",     ImageUrl = "https://image.hm.com/assets/hm/d8/65/d8651d1d12ff9a02d7d7034f05ed8d06ed50d83a.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 49, Title = "Baby Smocked Dress",     Description = "Delicate smocked cotton dress",    ImageUrl = "https://image.hm.com/assets/hm/7b/33/7b33d1353452a261ea6ef4f1c0fa214e2b4cb0b7.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 50, Title = "Baby Terry Joggers",     Description = "Soft terry-cloth jogger pants",    ImageUrl = "https://image.hm.com/assets/hm/60/87/60870dadfcc29e8fb83d60bd0da326c649e677e8.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 51, Title = "Baby Printed Leggings",  Description = "Fun printed stretch leggings",     ImageUrl = "https://image.hm.com/assets/hm/00/9b/009badc880eac55dccf0a48bd0fb8f48642564aa.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 52, Title = "Baby Long-Sleeve Top",   Description = "Soft long-sleeve jersey top",      ImageUrl = "https://image.hm.com/assets/hm/a1/82/a182beecb2b7ae190ed14c3f7b2a1f3d41b3a648.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 14m },
                        new { Id = 53, Title = "Baby Zip Sleepsuit",     Description = "Cosy zip-fastening sleepsuit",     ImageUrl = "https://image.hm.com/assets/hm/cb/fd/cbfdd42d2ae250b84240b35ed1cec21f652c79b9.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 54, Title = "Baby Denim Set",         Description = "Cute denim jacket and trouser set",ImageUrl = "https://image.hm.com/assets/hm/9f/50/9f50289fb4dfd9f089101165011843d712927cd0.jpg?imwidth=1260", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 24m },
                        // Girls (original 6)
                        new { Id = 2,  Title = "Girls Floral Dress",     Description = "Pretty summer floral dress",       ImageUrl = "https://image.hm.com/assets/hm/ab/15/ab15b8cd3b78ac8ba76768f9223a104734884e52.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 6,  Title = "Girls Princess Dress",   Description = "Elegant princess party dress",     ImageUrl = "https://image.hm.com/assets/hm/de/a1/dea1c170d095bae1a29b0606b6c8574890f87d3e.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 35m },
                        new { Id = 8,  Title = "Girls Leggings",         Description = "Comfortable stretch leggings",     ImageUrl = "https://image.hm.com/assets/hm/4a/f1/4af1c886bf01af58765b5f9a23fc5b704b92460a.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 15m },
                        new { Id = 12, Title = "Girls Sundress",         Description = "Light summer sundress",            ImageUrl = "https://image.hm.com/assets/hm/9f/0e/9f0e60edfbc8d7676ff7c7d1efd9c91505c7644a.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 13, Title = "Girls Denim Skirt",      Description = "Classic denim mini skirt",         ImageUrl = "https://image.hm.com/assets/hm/e6/10/e61010dcc4134f59cf924bd16d37057ca1341391.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 14, Title = "Girls Puff Sleeve Top",  Description = "Trendy puff sleeve blouse",        ImageUrl = "https://image.hm.com/assets/hm/c6/38/c638eb92d0419205d9c79c2bfc03afa13785b5d0.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 20m },
                        // Girls (extra 15)
                        new { Id = 55, Title = "Girls Embroidered Blouse",Description = "Floral embroidered cotton blouse", ImageUrl = "https://image.hm.com/assets/hm/98/65/98652f9415cabc5ff3c0f3fa1da8363f268bddf3.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 56, Title = "Girls Pleated Skirt",    Description = "Pretty pleated midi skirt",        ImageUrl = "https://image.hm.com/assets/hm/f6/a4/f6a4628ff4e95b72d299ca89fca1a32630b6e60e.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 57, Title = "Girls Ruffle Top",       Description = "Sweet ruffle-trim woven top",      ImageUrl = "https://image.hm.com/assets/hm/54/80/548024730d8318c5e6f7825019b4fabb5c863946.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 20m },
                        new { Id = 58, Title = "Girls Floral Jumpsuit",  Description = "Breezy floral wide-leg jumpsuit",  ImageUrl = "https://image.hm.com/assets/hm/d2/10/d2105e0304ea90b6889809976e0dc7f1f5aafb96.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 59, Title = "Girls Striped T-Shirt",  Description = "Classic striped cotton tee",       ImageUrl = "https://image.hm.com/assets/hm/4c/4b/4c4bf3d062319d0cb0105bbe07429279b4e18e47.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 60, Title = "Girls Velvet Dress",     Description = "Elegant velvet party dress",       ImageUrl = "https://image.hm.com/assets/hm/75/28/7528ca97387e613f693fd30cf8eca320ccd18249.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 42m },
                        new { Id = 61, Title = "Girls Tie-Dye Hoodie",   Description = "Trendy tie-dye zip hoodie",        ImageUrl = "https://image.hm.com/assets/hm/14/d1/14d16be739a74579d3d444d582207291de231fab.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 62, Title = "Girls Printed Joggers",  Description = "Soft printed jersey joggers",      ImageUrl = "https://image.hm.com/assets/hm/70/10/701055386810b6eacef999ffd08091505074a7cb.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 63, Title = "Girls Denim Jacket",     Description = "Classic stone-washed denim jacket",ImageUrl = "https://image.hm.com/assets/hm/27/c8/27c8197972224ca42f051bbc057e172d92ea5d18.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 38m },
                        new { Id = 64, Title = "Girls Knit Cardigan",    Description = "Cosy open-front knit cardigan",    ImageUrl = "https://image.hm.com/assets/hm/14/bc/14bc0bfc778be9d28651e5c1cf0c50dc57190328.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 65, Title = "Girls Sequin Top",       Description = "Sparkly sequin party top",         ImageUrl = "https://image.hm.com/assets/hm/02/94/029443545c4bc9e858c02d0464bb83979ebd2627.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 26m },
                        new { Id = 66, Title = "Girls Wide-Leg Trousers",Description = "Relaxed wide-leg woven trousers",  ImageUrl = "https://image.hm.com/assets/hm/99/c4/99c41f96ad10243a77e929616819991282af2cf3.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 67, Title = "Girls Linen Shorts",     Description = "Lightweight linen pull-on shorts", ImageUrl = "https://image.hm.com/assets/hm/70/c6/70c6e76b648d167c01cc18287bea90368de6c96f.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 68, Title = "Girls Smocked Dress",    Description = "Pretty smocked cotton dress",      ImageUrl = "https://image.hm.com/assets/hm/7e/fa/7efabdd51642bc55f269013d409814214cc186c8.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 36m },
                        new { Id = 69, Title = "Girls Cargo Pants",      Description = "Practical multi-pocket cargo pants",ImageUrl = "https://image.hm.com/assets/hm/13/79/13791492d295b4dbe4914c53751da8524097dd4d.jpg?imwidth=1260", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 28m },
                        // Boys (original 7)
                        new { Id = 3,  Title = "Boys Denim Jeans",       Description = "Classic straight-fit jeans",       ImageUrl = "https://image.hm.com/assets/hm/4b/19/4b1928a639cd4e4661d4ecc41c0a1e03e27730e7.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 4,  Title = "Boys Summer Shorts",     Description = "Light cotton summer shorts",        ImageUrl = "https://image.hm.com/assets/hm/41/be/41bed8a23b34c5083aa8a0bbbc9755592c6f716b.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 7,  Title = "Boys Cargo Shorts",      Description = "Practical multi-pocket shorts",     ImageUrl = "https://image.hm.com/assets/hm/43/a3/43a3a8d8a832d2d8dd1ad9391904345c387ca380.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 15, Title = "Boys Polo Shirt",        Description = "Classic cotton polo shirt",         ImageUrl = "https://image.hm.com/assets/hm/b6/6e/b66eee7aa009d6f0a0e72b112bc4f99ea6af8d05.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 16, Title = "Boys Graphic Hoodie",    Description = "Cool graphic print hoodie",         ImageUrl = "https://image.hm.com/assets/hm/fa/68/fa6891f65019c07a31f6fe616ccf8e5e53dc26b0.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 17, Title = "Boys Chino Pants",       Description = "Smart casual chino trousers",       ImageUrl = "https://image.hm.com/assets/hm/30/31/3031eb8ab1421f329731d54b8b35b15f1c8b6711.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 18, Title = "Boys Baseball Tee",      Description = "Sporty baseball-style tee",         ImageUrl = "https://image.hm.com/assets/hm/0d/2a/0d2a9d03b5aca7b15f680726b3186520bd1513b6.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        // Boys (extra 14)
                        new { Id = 70, Title = "Boys Track Jacket",      Description = "Sporty zip-up track jacket",        ImageUrl = "https://image.hm.com/assets/hm/3a/c2/3ac259f71ba8aa0f00f24b485f7b403867906d46.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 36m },
                        new { Id = 71, Title = "Boys Printed Sweatshirt",Description = "Cool graphic print sweatshirt",     ImageUrl = "https://image.hm.com/assets/hm/48/52/485224f72c37e68cc038ab6258f17497c9f60df9.jpg",              KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 72, Title = "Boys Fleece Hoodie",     Description = "Warm soft-fleece pullover hoodie",  ImageUrl = "https://image.hm.com/assets/hm/26/13/26131d5d278c6ae384f39a28f82751f80cfe2398.jpg",              KidsCategoryId = 3, KidsProductTypeId = 1, Price = 32m },
                        new { Id = 73, Title = "Boys Slim Fit Jeans",    Description = "Modern slim-fit denim jeans",       ImageUrl = "https://image.hm.com/assets/hm/07/d1/07d1bd3ba0b07a100e305145a11366b902af4877.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 74, Title = "Boys Tech Joggers",      Description = "Lightweight tech-fabric joggers",   ImageUrl = "https://image.hm.com/assets/hm/af/fa/affa1f4d54b02148f78885a480ecf134c48358d5.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 75, Title = "Boys Linen Shirt",       Description = "Breezy linen short-sleeve shirt",   ImageUrl = "https://image.hm.com/assets/hm/89/6d/896d4847603dda4310814f210d29a80850550287.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 76, Title = "Boys Board Shorts",      Description = "Quick-dry patterned board shorts",  ImageUrl = "https://image.hm.com/assets/hm/4c/43/4c43460eaad395f95d5355014f708b84f363fc20.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 77, Title = "Boys Zip Fleece",        Description = "Cosy full-zip fleece top",          ImageUrl = "https://image.hm.com/assets/hm/ee/c9/eec90fc1e30eca86b6d5e5ceccc0dacba7d7e7fc.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 34m },
                        new { Id = 78, Title = "Boys Striped Tee",       Description = "Classic navy striped jersey tee",   ImageUrl = "https://image.hm.com/assets/hm/91/8e/918ea167ca1684dffa6226d7155201f9ad496ad8.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 79, Title = "Boys Utility Shorts",    Description = "Cargo-style utility shorts",        ImageUrl = "https://image.hm.com/assets/hm/6b/fb/6bfb18d84e07d78ddbe585acab20f1cded8cc239.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 80, Title = "Boys Quilted Jacket",    Description = "Padded quilted zip jacket",         ImageUrl = "https://image.hm.com/assets/hm/aa/b7/aab746f40e5f92895ddb564434bfca4e7d4beb2e.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 44m },
                        new { Id = 81, Title = "Boys Long-Sleeve Tee",   Description = "Soft jersey long-sleeve tee",       ImageUrl = "https://image.hm.com/assets/hm/ff/73/ff73fe3b24d6b102f95fb3b26c03082e4c33d4a5.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 82, Title = "Boys Sweatpants",        Description = "Comfortable elastic-waist joggers", ImageUrl = "https://image.hm.com/assets/hm/33/62/3362c401e242b81519e76f47bd0792deba934f25.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 28m },
                        new { Id = 83, Title = "Boys Printed Tee",       Description = "Fun graphic printed t-shirt",       ImageUrl = "https://image.hm.com/assets/hm/9c/f9/9cf926b0539bb6de80b13b9e22650fdacccf338b.jpg?imwidth=1260", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 18m });
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("KidsCategories");
                    b.HasData(
                        new { Id = 1, Name = "Baby" }, new { Id = 2, Name = "Girls" }, new { Id = 3, Name = "Boys" },
                        new { Id = 4, Name = "Sleepwear" }, new { Id = 5, Name = "Swimwear" },
                        new { Id = 6, Name = "Footwear" }, new { Id = 7, Name = "Accessories" }, new { Id = 8, Name = "Sale" });
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("CartId").HasColumnType("int");
                    b.Property<int>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("CartId");
                    b.HasIndex("ProductId");
                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.HasKey("Id");
                    b.ToTable("KidsProductTypes");
                    b.HasData(new { Id = 1, Name = "Boys" }, new { Id = 2, Name = "Girls" });
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<decimal>("TotalPrice").HasColumnType("decimal(18,2)");
                    b.Property<int>("UserId").HasColumnType("int");
                    b.HasKey("Id");
                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                    b.Property<int>("OrderId").HasColumnType("int");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                    b.Property<int>("ProductId").HasColumnType("int");
                    b.Property<int>("Quantity").HasColumnType("int");
                    b.HasKey("Id");
                    b.HasIndex("OrderId");
                    b.HasIndex("ProductId");
                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.HasOne("KidsCategory", "KidsCategory").WithMany("KidsCards").HasForeignKey("KidsCategoryId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsSection.Models.KidsProductType", "KidsProductType").WithMany("KidsCards").HasForeignKey("KidsProductTypeId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("KidsCategory");
                    b.Navigation("KidsProductType");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.HasOne("KidsSection.Models.Cart", "Cart").WithMany("CartItems").HasForeignKey("CartId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsCards", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Cart");
                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.HasOne("KidsSection.Models.Order", "Order").WithMany("OrderItems").HasForeignKey("OrderId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.HasOne("KidsCards", "Product").WithMany().HasForeignKey("ProductId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("Order");
                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsCategory", b => { b.Navigation("KidsCards"); });
            modelBuilder.Entity("KidsSection.Models.Cart", b => { b.Navigation("CartItems"); });
            modelBuilder.Entity("KidsSection.Models.KidsProductType", b => { b.Navigation("KidsCards"); });
            modelBuilder.Entity("KidsSection.Models.Order", b => { b.Navigation("OrderItems"); });
#pragma warning restore 612, 618
        }
    }
}
