// <auto-generated />
using System;
using KidsSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260607000001_UpdateKidsCategories")]
    partial class UpdateKidsCategories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidsCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("KidsProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KidsCategoryId");

                    b.HasIndex("KidsProductTypeId");

                    b.ToTable("KidsCards");

                    b.HasData(
                        // Baby
                        new { Id = 1,  Title = "Baby Striped Onesie",   Description = "Soft cotton striped onesie",      ImageUrl = "https://images.unsplash.com/photo-1522771930-78848d9293e8?w=400&q=80",   KidsCategoryId = 1, KidsProductTypeId = 1, Price = 12m },
                        new { Id = 5,  Title = "Baby Rainbow Bodysuit",  Description = "Colourful rainbow bodysuit",      ImageUrl = "https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?w=400&q=80", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 9,  Title = "Baby Girl Romper",       Description = "Cute floral baby romper",         ImageUrl = "https://images.unsplash.com/photo-1607227893600-9bc90f1ead82?w=400&q=80", KidsCategoryId = 1, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 10, Title = "Baby Boy Bodysuit",      Description = "Soft jersey baby bodysuit",       ImageUrl = "https://images.unsplash.com/photo-1574179618836-b7b81b2e1a4d?w=400&q=80", KidsCategoryId = 1, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 11, Title = "Baby Knit Set",          Description = "Cosy knitted 2-piece set",        ImageUrl = "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&q=80",   KidsCategoryId = 1, KidsProductTypeId = 2, Price = 22m },
                        // Girls
                        new { Id = 2,  Title = "Girls Floral Dress",     Description = "Pretty summer floral dress",      ImageUrl = "https://images.unsplash.com/photo-1508766917616-d22f3f1eea14?w=400&q=80", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 18m },
                        new { Id = 6,  Title = "Girls Princess Dress",   Description = "Elegant princess party dress",    ImageUrl = "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&q=80", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 25m },
                        new { Id = 8,  Title = "Girls Leggings",         Description = "Comfortable stretch leggings",    ImageUrl = "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?w=400&q=80",   KidsCategoryId = 2, KidsProductTypeId = 2, Price = 15m },
                        new { Id = 12, Title = "Girls Sundress",         Description = "Light summer sundress",           ImageUrl = "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=400&q=80", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 32m },
                        new { Id = 13, Title = "Girls Denim Skirt",      Description = "Classic denim mini skirt",        ImageUrl = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 24m },
                        new { Id = 14, Title = "Girls Puff Sleeve Top",  Description = "Trendy puff sleeve blouse",       ImageUrl = "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=400&q=80", KidsCategoryId = 2, KidsProductTypeId = 2, Price = 20m },
                        // Boys
                        new { Id = 3,  Title = "Boys Denim Jeans",       Description = "Classic straight-fit jeans",     ImageUrl = "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 4,  Title = "Boys Summer Shorts",     Description = "Light cotton summer shorts",      ImageUrl = "https://images.unsplash.com/photo-1471286174890-9c112ac6f609?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 2, Price = 14m },
                        new { Id = 7,  Title = "Boys Cargo Shorts",      Description = "Practical multi-pocket shorts",   ImageUrl = "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 15, Title = "Boys Polo Shirt",        Description = "Classic cotton polo shirt",       ImageUrl = "https://images.unsplash.com/photo-1519689373923-95a9fa831f2e?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 16, Title = "Boys Graphic Hoodie",    Description = "Cool graphic print hoodie",       ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80",   KidsCategoryId = 3, KidsProductTypeId = 1, Price = 30m },
                        new { Id = 17, Title = "Boys Chino Pants",       Description = "Smart casual chino trousers",     ImageUrl = "https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 26m },
                        new { Id = 18, Title = "Boys Baseball Tee",      Description = "Sporty baseball-style tee",       ImageUrl = "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&q=80", KidsCategoryId = 3, KidsProductTypeId = 1, Price = 16m },
                        // Sleepwear
                        new { Id = 19, Title = "Girls Star Pyjamas",     Description = "Soft star-print pyjama set",      ImageUrl = "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&q=80", KidsCategoryId = 4, KidsProductTypeId = 2, Price = 22m },
                        new { Id = 20, Title = "Boys Dino Pyjamas",      Description = "Fun dinosaur pyjama set",         ImageUrl = "https://images.unsplash.com/photo-1586105449897-20b5efeb3233?w=400&q=80", KidsCategoryId = 4, KidsProductTypeId = 1, Price = 22m },
                        new { Id = 21, Title = "Baby Sleepsuit",         Description = "Warm fleece baby sleepsuit",      ImageUrl = "https://images.unsplash.com/photo-1567578301402-c43d6dbef7de?w=400&q=80", KidsCategoryId = 4, KidsProductTypeId = 1, Price = 18m },
                        new { Id = 22, Title = "Girls Nightgown",        Description = "Cosy cotton nightgown",           ImageUrl = "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=400&q=80", KidsCategoryId = 4, KidsProductTypeId = 2, Price = 20m },
                        // Swimwear
                        new { Id = 23, Title = "Girls Swimsuit",         Description = "Bright one-piece swimsuit",       ImageUrl = "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=400&q=80", KidsCategoryId = 5, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 24, Title = "Boys Swim Shorts",       Description = "Quick-dry swim shorts",           ImageUrl = "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&q=80", KidsCategoryId = 5, KidsProductTypeId = 1, Price = 20m },
                        new { Id = 25, Title = "Girls Bikini Set",       Description = "Colourful two-piece bikini",      ImageUrl = "https://images.unsplash.com/photo-1550639525-c97d455acf70?w=400&q=80",   KidsCategoryId = 5, KidsProductTypeId = 2, Price = 30m },
                        // Footwear
                        new { Id = 26, Title = "Kids Sneakers",          Description = "Lightweight everyday sneakers",   ImageUrl = "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&q=80",   KidsCategoryId = 6, KidsProductTypeId = 1, Price = 38m },
                        new { Id = 27, Title = "Girls Sandals",          Description = "Strappy summer sandals",          ImageUrl = "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=400&q=80",   KidsCategoryId = 6, KidsProductTypeId = 2, Price = 28m },
                        new { Id = 28, Title = "Boys Canvas Shoes",      Description = "Classic canvas lace-up shoes",    ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80",   KidsCategoryId = 6, KidsProductTypeId = 1, Price = 32m },
                        new { Id = 29, Title = "Kids Rain Boots",        Description = "Waterproof rubber rain boots",    ImageUrl = "https://images.unsplash.com/photo-1597248881519-db089b3a0508?w=400&q=80", KidsCategoryId = 6, KidsProductTypeId = 2, Price = 34m },
                        // Accessories
                        new { Id = 30, Title = "Kids School Backpack",   Description = "Spacious padded school bag",      ImageUrl = "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80",   KidsCategoryId = 7, KidsProductTypeId = 1, Price = 35m },
                        new { Id = 31, Title = "Girls Hair Bow Set",     Description = "Set of 5 colourful hair bows",    ImageUrl = "https://images.unsplash.com/photo-1553361371-9b22f78e8b1d?w=400&q=80",   KidsCategoryId = 7, KidsProductTypeId = 2, Price = 12m },
                        new { Id = 32, Title = "Kids Sun Hat",           Description = "Wide-brim UV protection hat",     ImageUrl = "https://images.unsplash.com/photo-1485462537746-965f33f7f6a7?w=400&q=80", KidsCategoryId = 7, KidsProductTypeId = 1, Price = 16m },
                        new { Id = 33, Title = "Kids Sunglasses",        Description = "UV400 kids sunglasses",           ImageUrl = "https://images.unsplash.com/photo-1499002238440-d264edd596ec?w=400&q=80", KidsCategoryId = 7, KidsProductTypeId = 2, Price = 14m },
                        // Sale
                        new { Id = 34, Title = "Baby Patterned Onesie",  Description = "Adorable patterned baby onesie", ImageUrl = "https://images.unsplash.com/photo-1519689373923-95a9fa831f2e?w=400&q=80", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 20m, DiscountPercent = (int?)30 },
                        new { Id = 35, Title = "Girls Summer Dress",      Description = "Light floral girls dress",       ImageUrl = "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=400&q=80", KidsCategoryId = 8, KidsProductTypeId = 2, Price = 35m, DiscountPercent = (int?)25 },
                        new { Id = 36, Title = "Boys Zip Hoodie",         Description = "Warm zip-up boys hoodie",        ImageUrl = "https://images.unsplash.com/photo-1471286174890-9c112ac6f609?w=400&q=80", KidsCategoryId = 8, KidsProductTypeId = 1, Price = 32m, DiscountPercent = (int?)20 },
                        new { Id = 37, Title = "Kids Canvas Trainers",    Description = "Classic canvas trainers",        ImageUrl = "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=400&q=80",   KidsCategoryId = 8, KidsProductTypeId = 2, Price = 40m, DiscountPercent = (int?)35 });
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsCategories");

                    b.HasData(
                        new { Id = 1, Name = "Baby" },
                        new { Id = 2, Name = "Girls" },
                        new { Id = 3, Name = "Boys" },
                        new { Id = 4, Name = "Sleepwear" },
                        new { Id = 5, Name = "Swimwear" },
                        new { Id = 6, Name = "Footwear" },
                        new { Id = 7, Name = "Accessories" },
                        new { Id = 8, Name = "Sale" });
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsProductTypes");

                    b.HasData(
                        new { Id = 1, Name = "Boys" },
                        new { Id = 2, Name = "Girls" });
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.HasOne("KidsCategory", "KidsCategory")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsSection.Models.KidsProductType", "KidsProductType")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KidsCategory");

                    b.Navigation("KidsProductType");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.HasOne("KidsSection.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.HasOne("KidsSection.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
