// <auto-generated />
using System;
using KidsSection.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidsSection.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260604202224_AddDiscountPercent")]
    partial class AddDiscountPercent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KidsCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("KidsProductTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KidsCategoryId");

                    b.HasIndex("KidsProductTypeId");

                    b.ToTable("KidsCards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Colorful striped t-shirt",
                            ImageUrl = "https://images.unsplash.com/photo-1519689373923-95a9fa831f2e?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 1,
                            Price = 12m,
                            Title = "Striped T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pretty floral dress",
                            ImageUrl = "https://images.unsplash.com/photo-1508766917616-d22f3f1eea14?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 18m,
                            Title = "Floral Dress"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Classic denim jeans",
                            ImageUrl = "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 1,
                            Price = 22m,
                            Title = "Denim Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Light summer shorts",
                            ImageUrl = "https://images.unsplash.com/photo-1471286174890-9c112ac6f609?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 2,
                            Price = 14m,
                            Title = "Summer Shorts"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Fun rainbow hoodie",
                            ImageUrl = "https://images.unsplash.com/photo-1556821840-3a63f15732ce?w=400&q=80",
                            KidsCategoryId = 1,
                            KidsProductTypeId = 1,
                            Price = 20m,
                            Title = "Rainbow Hoodie"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Lovely princess dress",
                            ImageUrl = "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=400&q=80",
                            KidsCategoryId = 2,
                            KidsProductTypeId = 2,
                            Price = 25m,
                            Title = "Princess Dress"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Practical cargo shorts",
                            ImageUrl = "https://images.unsplash.com/photo-1591195853828-11db59a44f43?w=400&q=80",
                            KidsCategoryId = 4,
                            KidsProductTypeId = 1,
                            Price = 16m,
                            Title = "Cargo Shorts"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Comfortable leggings",
                            ImageUrl = "https://images.unsplash.com/photo-1543087903-1ac2ec7aa8c5?w=400&q=80",
                            KidsCategoryId = 3,
                            KidsProductTypeId = 2,
                            Price = 15m,
                            Title = "Leggings"
                        });
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "T-Shirts"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dresses"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jeans"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shorts"
                        });
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KidsProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Boys"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Girls"
                        });
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("KidsCards", b =>
                {
                    b.HasOne("KidsCategory", "KidsCategory")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsSection.Models.KidsProductType", "KidsProductType")
                        .WithMany("KidsCards")
                        .HasForeignKey("KidsProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KidsCategory");

                    b.Navigation("KidsProductType");
                });

            modelBuilder.Entity("KidsSection.Models.CartItem", b =>
                {
                    b.HasOne("KidsSection.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsSection.Models.OrderItem", b =>
                {
                    b.HasOne("KidsSection.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KidsCards", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KidsCategory", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("KidsSection.Models.KidsProductType", b =>
                {
                    b.Navigation("KidsCards");
                });

            modelBuilder.Entity("KidsSection.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
